/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerimeterRouteImport } from './routes/perimeter'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ElderlyRouteImport } from './routes/elderly'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< HEAD
import { Route as IncidentsPerimeterRouteImport } from './routes/incidents.perimeter'
import { Route as EventsPackageRouteImport } from './routes/events.package'
=======
import { Route as ResidentIndexRouteImport } from './routes/resident.index'
import { Route as FamilyIndexRouteImport } from './routes/family.index'
import { Route as ResidentSupportRouteImport } from './routes/resident.support'
import { Route as ResidentNotifiedRouteImport } from './routes/resident.notified'
import { Route as ResidentCheckInRouteImport } from './routes/resident.check-in'
import { Route as FamilySupportRouteImport } from './routes/family.support'
import { Route as FamilyAlertRouteImport } from './routes/family.alert'
>>>>>>> e6c874ee848cc61b9e38eed57db96f506df3bf21

const PerimeterRoute = PerimeterRouteImport.update({
  id: '/perimeter',
  path: '/perimeter',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderlyRoute = ElderlyRouteImport.update({
  id: '/elderly',
  path: '/elderly',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const IncidentsPerimeterRoute = IncidentsPerimeterRouteImport.update({
  id: '/incidents/perimeter',
  path: '/incidents/perimeter',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPackageRoute = EventsPackageRouteImport.update({
  id: '/events/package',
  path: '/events/package',
=======
const ResidentIndexRoute = ResidentIndexRouteImport.update({
  id: '/resident/',
  path: '/resident/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyIndexRoute = FamilyIndexRouteImport.update({
  id: '/family/',
  path: '/family/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentSupportRoute = ResidentSupportRouteImport.update({
  id: '/resident/support',
  path: '/resident/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentNotifiedRoute = ResidentNotifiedRouteImport.update({
  id: '/resident/notified',
  path: '/resident/notified',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentCheckInRoute = ResidentCheckInRouteImport.update({
  id: '/resident/check-in',
  path: '/resident/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilySupportRoute = FamilySupportRouteImport.update({
  id: '/family/support',
  path: '/family/support',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyAlertRoute = FamilyAlertRouteImport.update({
  id: '/family/alert',
  path: '/family/alert',
>>>>>>> e6c874ee848cc61b9e38eed57db96f506df3bf21
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/access': typeof AccessRoute
  '/clusters': typeof ClustersRoute
  '/elderly': typeof ElderlyRoute
  '/notifications': typeof NotificationsRoute
  '/perimeter': typeof PerimeterRoute
  '/events/package': typeof EventsPackageRoute
  '/incidents/perimeter': typeof IncidentsPerimeterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/clusters': typeof ClustersRoute
  '/elderly': typeof ElderlyRoute
  '/notifications': typeof NotificationsRoute
  '/perimeter': typeof PerimeterRoute
  '/events/package': typeof EventsPackageRoute
  '/incidents/perimeter': typeof IncidentsPerimeterRoute
=======
  '/family/alert': typeof FamilyAlertRoute
  '/family/support': typeof FamilySupportRoute
  '/resident/check-in': typeof ResidentCheckInRoute
  '/resident/notified': typeof ResidentNotifiedRoute
  '/resident/support': typeof ResidentSupportRoute
  '/family/': typeof FamilyIndexRoute
  '/resident/': typeof ResidentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/family/alert': typeof FamilyAlertRoute
  '/family/support': typeof FamilySupportRoute
  '/resident/check-in': typeof ResidentCheckInRoute
  '/resident/notified': typeof ResidentNotifiedRoute
  '/resident/support': typeof ResidentSupportRoute
  '/family': typeof FamilyIndexRoute
  '/resident': typeof ResidentIndexRoute
>>>>>>> e6c874ee848cc61b9e38eed57db96f506df3bf21
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/access': typeof AccessRoute
  '/clusters': typeof ClustersRoute
  '/elderly': typeof ElderlyRoute
  '/notifications': typeof NotificationsRoute
  '/perimeter': typeof PerimeterRoute
  '/events/package': typeof EventsPackageRoute
  '/incidents/perimeter': typeof IncidentsPerimeterRoute
=======
  '/family/alert': typeof FamilyAlertRoute
  '/family/support': typeof FamilySupportRoute
  '/resident/check-in': typeof ResidentCheckInRoute
  '/resident/notified': typeof ResidentNotifiedRoute
  '/resident/support': typeof ResidentSupportRoute
  '/family/': typeof FamilyIndexRoute
  '/resident/': typeof ResidentIndexRoute
>>>>>>> e6c874ee848cc61b9e38eed57db96f506df3bf21
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
<<<<<<< HEAD
    | '/access'
    | '/clusters'
    | '/elderly'
    | '/notifications'
    | '/perimeter'
    | '/events/package'
    | '/incidents/perimeter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/clusters'
    | '/elderly'
    | '/notifications'
    | '/perimeter'
    | '/events/package'
    | '/incidents/perimeter'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/clusters'
    | '/elderly'
    | '/notifications'
    | '/perimeter'
    | '/events/package'
    | '/incidents/perimeter'
=======
    | '/family/alert'
    | '/family/support'
    | '/resident/check-in'
    | '/resident/notified'
    | '/resident/support'
    | '/family/'
    | '/resident/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/family/alert'
    | '/family/support'
    | '/resident/check-in'
    | '/resident/notified'
    | '/resident/support'
    | '/family'
    | '/resident'
  id:
    | '__root__'
    | '/'
    | '/family/alert'
    | '/family/support'
    | '/resident/check-in'
    | '/resident/notified'
    | '/resident/support'
    | '/family/'
    | '/resident/'
>>>>>>> e6c874ee848cc61b9e38eed57db96f506df3bf21
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  AccessRoute: typeof AccessRoute
  ClustersRoute: typeof ClustersRoute
  ElderlyRoute: typeof ElderlyRoute
  NotificationsRoute: typeof NotificationsRoute
  PerimeterRoute: typeof PerimeterRoute
  EventsPackageRoute: typeof EventsPackageRoute
  IncidentsPerimeterRoute: typeof IncidentsPerimeterRoute
=======
  FamilyAlertRoute: typeof FamilyAlertRoute
  FamilySupportRoute: typeof FamilySupportRoute
  ResidentCheckInRoute: typeof ResidentCheckInRoute
  ResidentNotifiedRoute: typeof ResidentNotifiedRoute
  ResidentSupportRoute: typeof ResidentSupportRoute
  FamilyIndexRoute: typeof FamilyIndexRoute
  ResidentIndexRoute: typeof ResidentIndexRoute
>>>>>>> e6c874ee848cc61b9e38eed57db96f506df3bf21
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perimeter': {
      id: '/perimeter'
      path: '/perimeter'
      fullPath: '/perimeter'
      preLoaderRoute: typeof PerimeterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elderly': {
      id: '/elderly'
      path: '/elderly'
      fullPath: '/elderly'
      preLoaderRoute: typeof ElderlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/incidents/perimeter': {
      id: '/incidents/perimeter'
      path: '/incidents/perimeter'
      fullPath: '/incidents/perimeter'
      preLoaderRoute: typeof IncidentsPerimeterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/package': {
      id: '/events/package'
      path: '/events/package'
      fullPath: '/events/package'
      preLoaderRoute: typeof EventsPackageRouteImport
=======
    '/resident/': {
      id: '/resident/'
      path: '/resident'
      fullPath: '/resident/'
      preLoaderRoute: typeof ResidentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/': {
      id: '/family/'
      path: '/family'
      fullPath: '/family/'
      preLoaderRoute: typeof FamilyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/support': {
      id: '/resident/support'
      path: '/resident/support'
      fullPath: '/resident/support'
      preLoaderRoute: typeof ResidentSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/notified': {
      id: '/resident/notified'
      path: '/resident/notified'
      fullPath: '/resident/notified'
      preLoaderRoute: typeof ResidentNotifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/check-in': {
      id: '/resident/check-in'
      path: '/resident/check-in'
      fullPath: '/resident/check-in'
      preLoaderRoute: typeof ResidentCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/support': {
      id: '/family/support'
      path: '/family/support'
      fullPath: '/family/support'
      preLoaderRoute: typeof FamilySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/alert': {
      id: '/family/alert'
      path: '/family/alert'
      fullPath: '/family/alert'
      preLoaderRoute: typeof FamilyAlertRouteImport
>>>>>>> e6c874ee848cc61b9e38eed57db96f506df3bf21
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  AccessRoute: AccessRoute,
  ClustersRoute: ClustersRoute,
  ElderlyRoute: ElderlyRoute,
  NotificationsRoute: NotificationsRoute,
  PerimeterRoute: PerimeterRoute,
  EventsPackageRoute: EventsPackageRoute,
  IncidentsPerimeterRoute: IncidentsPerimeterRoute,
=======
  FamilyAlertRoute: FamilyAlertRoute,
  FamilySupportRoute: FamilySupportRoute,
  ResidentCheckInRoute: ResidentCheckInRoute,
  ResidentNotifiedRoute: ResidentNotifiedRoute,
  ResidentSupportRoute: ResidentSupportRoute,
  FamilyIndexRoute: FamilyIndexRoute,
  ResidentIndexRoute: ResidentIndexRoute,
>>>>>>> e6c874ee848cc61b9e38eed57db96f506df3bf21
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
