/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerimeterRouteImport } from './routes/perimeter'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ElderlyRouteImport } from './routes/elderly'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentsPerimeterRouteImport } from './routes/incidents.perimeter'
import { Route as EventsPackageRouteImport } from './routes/events.package'

const PerimeterRoute = PerimeterRouteImport.update({
  id: '/perimeter',
  path: '/perimeter',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderlyRoute = ElderlyRouteImport.update({
  id: '/elderly',
  path: '/elderly',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsPerimeterRoute = IncidentsPerimeterRouteImport.update({
  id: '/incidents/perimeter',
  path: '/incidents/perimeter',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPackageRoute = EventsPackageRouteImport.update({
  id: '/events/package',
  path: '/events/package',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/clusters': typeof ClustersRoute
  '/elderly': typeof ElderlyRoute
  '/notifications': typeof NotificationsRoute
  '/perimeter': typeof PerimeterRoute
  '/events/package': typeof EventsPackageRoute
  '/incidents/perimeter': typeof IncidentsPerimeterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/clusters': typeof ClustersRoute
  '/elderly': typeof ElderlyRoute
  '/notifications': typeof NotificationsRoute
  '/perimeter': typeof PerimeterRoute
  '/events/package': typeof EventsPackageRoute
  '/incidents/perimeter': typeof IncidentsPerimeterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/clusters': typeof ClustersRoute
  '/elderly': typeof ElderlyRoute
  '/notifications': typeof NotificationsRoute
  '/perimeter': typeof PerimeterRoute
  '/events/package': typeof EventsPackageRoute
  '/incidents/perimeter': typeof IncidentsPerimeterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/clusters'
    | '/elderly'
    | '/notifications'
    | '/perimeter'
    | '/events/package'
    | '/incidents/perimeter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/clusters'
    | '/elderly'
    | '/notifications'
    | '/perimeter'
    | '/events/package'
    | '/incidents/perimeter'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/clusters'
    | '/elderly'
    | '/notifications'
    | '/perimeter'
    | '/events/package'
    | '/incidents/perimeter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  ClustersRoute: typeof ClustersRoute
  ElderlyRoute: typeof ElderlyRoute
  NotificationsRoute: typeof NotificationsRoute
  PerimeterRoute: typeof PerimeterRoute
  EventsPackageRoute: typeof EventsPackageRoute
  IncidentsPerimeterRoute: typeof IncidentsPerimeterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perimeter': {
      id: '/perimeter'
      path: '/perimeter'
      fullPath: '/perimeter'
      preLoaderRoute: typeof PerimeterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elderly': {
      id: '/elderly'
      path: '/elderly'
      fullPath: '/elderly'
      preLoaderRoute: typeof ElderlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/perimeter': {
      id: '/incidents/perimeter'
      path: '/incidents/perimeter'
      fullPath: '/incidents/perimeter'
      preLoaderRoute: typeof IncidentsPerimeterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/package': {
      id: '/events/package'
      path: '/events/package'
      fullPath: '/events/package'
      preLoaderRoute: typeof EventsPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  ClustersRoute: ClustersRoute,
  ElderlyRoute: ElderlyRoute,
  NotificationsRoute: NotificationsRoute,
  PerimeterRoute: PerimeterRoute,
  EventsPackageRoute: EventsPackageRoute,
  IncidentsPerimeterRoute: IncidentsPerimeterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
