/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidentIndexRouteImport } from './routes/resident.index'
import { Route as FamilyIndexRouteImport } from './routes/family.index'
import { Route as ResidentSupportRouteImport } from './routes/resident.support'
import { Route as ResidentNotifiedRouteImport } from './routes/resident.notified'
import { Route as ResidentCheckInRouteImport } from './routes/resident.check-in'
import { Route as FamilySupportRouteImport } from './routes/family.support'
import { Route as FamilyAlertRouteImport } from './routes/family.alert'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentIndexRoute = ResidentIndexRouteImport.update({
  id: '/resident/',
  path: '/resident/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyIndexRoute = FamilyIndexRouteImport.update({
  id: '/family/',
  path: '/family/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentSupportRoute = ResidentSupportRouteImport.update({
  id: '/resident/support',
  path: '/resident/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentNotifiedRoute = ResidentNotifiedRouteImport.update({
  id: '/resident/notified',
  path: '/resident/notified',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentCheckInRoute = ResidentCheckInRouteImport.update({
  id: '/resident/check-in',
  path: '/resident/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilySupportRoute = FamilySupportRouteImport.update({
  id: '/family/support',
  path: '/family/support',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyAlertRoute = FamilyAlertRouteImport.update({
  id: '/family/alert',
  path: '/family/alert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/family/alert': typeof FamilyAlertRoute
  '/family/support': typeof FamilySupportRoute
  '/resident/check-in': typeof ResidentCheckInRoute
  '/resident/notified': typeof ResidentNotifiedRoute
  '/resident/support': typeof ResidentSupportRoute
  '/family/': typeof FamilyIndexRoute
  '/resident/': typeof ResidentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/family/alert': typeof FamilyAlertRoute
  '/family/support': typeof FamilySupportRoute
  '/resident/check-in': typeof ResidentCheckInRoute
  '/resident/notified': typeof ResidentNotifiedRoute
  '/resident/support': typeof ResidentSupportRoute
  '/family': typeof FamilyIndexRoute
  '/resident': typeof ResidentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/family/alert': typeof FamilyAlertRoute
  '/family/support': typeof FamilySupportRoute
  '/resident/check-in': typeof ResidentCheckInRoute
  '/resident/notified': typeof ResidentNotifiedRoute
  '/resident/support': typeof ResidentSupportRoute
  '/family/': typeof FamilyIndexRoute
  '/resident/': typeof ResidentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/family/alert'
    | '/family/support'
    | '/resident/check-in'
    | '/resident/notified'
    | '/resident/support'
    | '/family/'
    | '/resident/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/family/alert'
    | '/family/support'
    | '/resident/check-in'
    | '/resident/notified'
    | '/resident/support'
    | '/family'
    | '/resident'
  id:
    | '__root__'
    | '/'
    | '/family/alert'
    | '/family/support'
    | '/resident/check-in'
    | '/resident/notified'
    | '/resident/support'
    | '/family/'
    | '/resident/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamilyAlertRoute: typeof FamilyAlertRoute
  FamilySupportRoute: typeof FamilySupportRoute
  ResidentCheckInRoute: typeof ResidentCheckInRoute
  ResidentNotifiedRoute: typeof ResidentNotifiedRoute
  ResidentSupportRoute: typeof ResidentSupportRoute
  FamilyIndexRoute: typeof FamilyIndexRoute
  ResidentIndexRoute: typeof ResidentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/': {
      id: '/resident/'
      path: '/resident'
      fullPath: '/resident/'
      preLoaderRoute: typeof ResidentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/': {
      id: '/family/'
      path: '/family'
      fullPath: '/family/'
      preLoaderRoute: typeof FamilyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/support': {
      id: '/resident/support'
      path: '/resident/support'
      fullPath: '/resident/support'
      preLoaderRoute: typeof ResidentSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/notified': {
      id: '/resident/notified'
      path: '/resident/notified'
      fullPath: '/resident/notified'
      preLoaderRoute: typeof ResidentNotifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/check-in': {
      id: '/resident/check-in'
      path: '/resident/check-in'
      fullPath: '/resident/check-in'
      preLoaderRoute: typeof ResidentCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/support': {
      id: '/family/support'
      path: '/family/support'
      fullPath: '/family/support'
      preLoaderRoute: typeof FamilySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/alert': {
      id: '/family/alert'
      path: '/family/alert'
      fullPath: '/family/alert'
      preLoaderRoute: typeof FamilyAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamilyAlertRoute: FamilyAlertRoute,
  FamilySupportRoute: FamilySupportRoute,
  ResidentCheckInRoute: ResidentCheckInRoute,
  ResidentNotifiedRoute: ResidentNotifiedRoute,
  ResidentSupportRoute: ResidentSupportRoute,
  FamilyIndexRoute: FamilyIndexRoute,
  ResidentIndexRoute: ResidentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
